### ISSUE TITLE
Ensure that user metrics are tagged sufficiently differently from FTL core metrics

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1816] opened 2024-06-17 23:18 UTC
They might need a different "app" or something? Not sure.

**Comment by bradleydwyer** [comment] 2024-07-09 00:13
Use the project name from the toml to add a tag to logs and metrics sent to Datadog - for non FTL events/logs.

**Comment by wesbillman** [comment] 2024-07-15 23:37
Duplicate of #2023

**Closed** 2024-08-05 19:22 UTC
Labels: P2
