### ISSUE TITLE
`ftl call` cryptic failure if an expected arg isn't present

### ISSUE THREAD

**Issue by safeer** [TBD54566975/ftl#2848] opened 2024-09-26 20:52 UTC
```go
type MissionResultRequest struct {
	AgentID    float64 `json:"agent_id"`
	Successful bool    `json:"successful"`
}

//ftl:verb export
func MissionResult(ctx context.Context, req MissionResultRequest) (MissionResultResponse, error) {
	...
}
```

When called with an arg `agent_id` instead of `agentId`, the error is cryptic:
```sh
> ftl call relay.missionResult '{"agent_id": 7, "successful": true}'
ftl: error: verb error: invalid request to verb relay.missionResult: expected string key, got float64
```

**Comment by wesbillman** [comment] 2024-09-26 23:21
I think this is our expected behavior here since `ftl call` doesn't go through our `ingress` layer and therefore doesn't use the `json` aliases. There might be updates in the future around this area if we don't need different json vs. FTL encoding but for now, this is how `ftl call` works.

We could put effort into improving the error messaging here, but it's likely going to get overhauled in a future refactor so I'll close this out for now.

**Closed by wesbillman** 2024-09-26 23:21 UTC
Labels: dx
