### ISSUE TITLE
Add additional events for cron jobs

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1260] opened 2024-04-15 04:48 UTC
Events like:
"could not build body for cron job"
"Could not kill stale cron job %q because schedule could not be parsed: %q"

> all of these log messages should be associated with the cron job in the events table so that the user can filter and find issues with their cron jobs.

**Comment by matt2e** [comment] 2024-04-30 01:56
This may end up being rolled into async calls work

**Comment by safeer** [comment] 2024-09-25 20:47
Cron is rewritten to use async_calls, so this is a dupe of #2473

**Closed by safeer** 2024-09-25 20:47 UTC
