### ISSUE TITLE
Validate uploaded artifacts at deployment

### ISSUE THREAD

**Issue by jvmakine** [TBD54566975/ftl#3250] opened 2024-10-30 04:44 UTC
Currently, if we upload an invalid binary (compiled for incorrect architecture, for example) the deployment just hangs, and runner ends up in crash loop, with error
```
ftl-runner: error: failed to spawn plugin: plugin process died: context canceled
```

It would be a better user experience to check the binary is in correct format, and if not, return an error indicating that during the deployment.

**Comment by alecthomas** [comment] 2024-10-30 07:12
Duplicate of #1845

**Closed by alecthomas** 2024-10-30 07:12 UTC
Labels: triage
