### ISSUE TITLE
Error viewing module schema in Console

### ISSUE THREAD

**Issue by tomdaffurn** [TBD54566975/ftl#2754] opened 2024-09-20 04:58 UTC
Click the arrow next to a module name several times. The 3rd click causes this error:

```
Unexpected Application Error!
Rendered more hooks than during the previous render.
Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (http://localhost:8892/node_modules/.vite/deps/chunk-UVB5XM2J.js?v=2af07823:11678:21)
    at updateRef (http://localhost:8892/node_modules/.vite/deps/chunk-UVB5XM2J.js?v=2af07823:12064:22)
    at Object.useRef (http://localhost:8892/node_modules/.vite/deps/chunk-UVB5XM2J.js?v=2af07823:12745:22)
    at Object.useRef (http://localhost:8892/node_modules/.vite/deps/chunk-5FAUR5XI.js?v=2af07823:1074:29)
    at useNavigateStable (http://localhost:8892/node_modules/.vite/deps/react-router-dom.js?v=a2b19b81:4366:25)
    at useNavigate (http://localhost:8892/node_modules/.vite/deps/react-router-dom.js?v=a2b19b81:3859:24)
    at DeclLink (http://localhost:8892/src/features/modules/decls/DeclLink.tsx:78:20)
    at renderWithHooks (http://localhost:8892/node_modules/.vite/deps/chunk-UVB5XM2J.js?v=2af07823:11548:26)
    at updateFunctionComponent (http://localhost:8892/node_modules/.vite/deps/chunk-UVB5XM2J.js?v=2af07823:14582:28)
    at beginWork (http://localhost:8892/node_modules/.vite/deps/chunk-UVB5XM2J.js?v=2af07823:15924:22)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

Repro:
<img width="364" alt="Screenshot 2024-09-20 at 2 52 39 PM" src="https://github.com/user-attachments/assets/07d1ee2d-6852-43e4-bf4e-5040b38cf8b5">

**Comment by deniseli** [comment] 2024-09-24 19:47
Closing for now since none of us could reproduce it, but I also remember seeing this in the past so if anyone catches this, please let me know :)

**Closed by deniseli** 2024-09-24 19:47 UTC
Labels: bug, console
