### ISSUE TITLE
Explore error cases caused by case changes when parsing schema

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1497] opened 2024-05-15 22:44 UTC
I don't know any exact cases, this ticket is about finding the different permutations.
When writing a module, you can use different cases for a name which then may get conflated as we standardise those names in the ftl schema.
I don't think we would error in schema parsing, so we'd end up with weird results...

eg:
```
type UserId string
type UserID int

var someDID = ftl.Secret...
var someDid = ftl.Secret...
```

**Comment by alecthomas** [comment] 2024-05-15 23:02
I think this is related to #1482, in that we would disallow `UserID` and `SomeDID`.

**Comment by wesbillman** [comment] 2024-05-16 22:25
Duplicate of #1482

**Closed by wesbillman** 2024-05-16 22:25 UTC
Labels: duplicate
